openapi: 3.0.1
info:
  title: ReportPortal
  description: Report Portal UAT documentation
  contact:
    name: Support
    email: support@reportportal.io
  license:
    name: Apache 2.0SupportEPMC-TSTReportPortal@epam.com
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 5.11.0
servers:
  - url: '{protocol}://{authority}/uat'
    description: ReportPortal UAT server
    variables:
      protocol:
        default: https
        description: Protocol
        enum:
          - http
          - https
      authority:
        description: Host name and port (if needed) of Report Portal server
        default: demo.reportportal.io
tags:
- name: auth-configuration-endpoint
  description: Auth Configuration Endpoint
- name: github-endpoint
  description: Github Endpoint
- name: o-auth-configuration-endpoint
  description: O Auth Configuration Endpoint
- name: sso-endpoint
  description: Sso Endpoint
paths:
  /settings/auth/{authType}:
    get:
      tags:
      - auth-configuration-endpoint
      summary: Retrieves auth settings
      operationId: getSettingsUsingGET
      parameters:
      - name: authType
        in: path
        description: authType
        required: true
        schema:
          type: string
          enum:
          - ad
          - ldap
          - saml
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AbstractAuthResource'
      deprecated: false
    post:
      tags:
      - auth-configuration-endpoint
      summary: Create new auth integration
      operationId: createAuthIntegrationUsingPOST
      parameters:
      - name: authType
        in: path
        description: authType
        required: true
        schema:
          type: string
          enum:
          - ad
          - ldap
          - saml
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthRQ'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AbstractAuthResource'
      deprecated: false
      x-codegen-request-body-name: request
  /settings/auth/{authType}/{integrationId}:
    put:
      tags:
      - auth-configuration-endpoint
      summary: Update auth integration
      operationId: updateAuthIntegrationUsingPUT
      parameters:
      - name: authType
        in: path
        description: authType
        required: true
        schema:
          type: string
          enum:
          - ad
          - ldap
          - saml
      - name: integrationId
        in: path
        description: integrationId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthRQ'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AbstractAuthResource'
      deprecated: false
      x-codegen-request-body-name: request
  /settings/auth/{integrationId}:
    delete:
      tags:
      - auth-configuration-endpoint
      summary: Retrieves auth settings
      operationId: deleteSettingsUsingDELETE
      parameters:
      - name: integrationId
        in: path
        description: integrationId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OperationCompletionRS'
      deprecated: false
  /settings/oauth:
    get:
      tags:
      - o-auth-configuration-endpoint
      summary: Returns OAuth Server Settings
      operationId: getOAuthSettingsUsingGET_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/OAuthRegistrationResource'
      deprecated: false
  /settings/oauth/{authId}:
    get:
      tags:
      - o-auth-configuration-endpoint
      summary: Returns OAuth Server Settings
      operationId: getOAuthSettingsUsingGET
      parameters:
      - name: authId
        in: path
        description: authId
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OAuthRegistrationResource'
      deprecated: false
    put:
      tags:
      - o-auth-configuration-endpoint
      summary: Creates/Updates OAuth Integration Settings
      operationId: updateOAuthSettingsUsingPUT
      parameters:
      - name: authId
        in: path
        description: authId
        required: true
        schema:
          type: string
      requestBody:
        description: clientRegistrationResource
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthRegistrationResource'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OAuthRegistrationResource'
      deprecated: false
      x-codegen-request-body-name: clientRegistrationResource
    post:
      tags:
      - o-auth-configuration-endpoint
      summary: Creates/Updates OAuth Integration Settings
      operationId: updateOAuthSettingsUsingPOST
      parameters:
      - name: authId
        in: path
        description: authId
        required: true
        schema:
          type: string
      requestBody:
        description: clientRegistrationResource
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthRegistrationResource'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OAuthRegistrationResource'
      deprecated: false
      x-codegen-request-body-name: clientRegistrationResource
    delete:
      tags:
      - o-auth-configuration-endpoint
      summary: Deletes OAuth Integration Settings
      operationId: deleteOAuthSettingUsingDELETE
      parameters:
      - name: authId
        in: path
        description: authId
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OperationCompletionRS'
      deprecated: false
  /sso/me:
    get:
      tags:
      - sso-endpoint
      summary: user
      operationId: userUsingGET
      parameters:
      - name: authenticated
        in: query
        schema:
          type: boolean
      - name: "authorities[0].authority"
        in: query
        schema:
          type: string
      - name: credentials
        in: query
        schema:
          type: object
      - name: details
        in: query
        schema:
          type: object
      - name: principal
        in: query
        schema:
          type: object
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
    post:
      tags:
      - sso-endpoint
      summary: user
      operationId: userUsingPOST
      parameters:
      - name: authenticated
        in: query
        schema:
          type: boolean
      - name: "authorities[0].authority"
        in: query
        schema:
          type: string
      - name: credentials
        in: query
        schema:
          type: object
      - name: details
        in: query
        schema:
          type: object
      - name: principal
        in: query
        schema:
          type: object
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
  /sso/me/github/synchronize:
    post:
      tags:
      - github-endpoint
      summary: Synchronizes logged-in GitHub user
      operationId: synchronizeUsingPOST
      parameters:
      - name: OAuth2Request.approved
        in: query
        schema:
          type: boolean
      - name: "OAuth2Request.authorities[0].authority"
        in: query
        schema:
          type: string
      - name: OAuth2Request.grantType
        in: query
        schema:
          type: string
      - name: OAuth2Request.redirectUri
        in: query
        schema:
          type: string
      - name: OAuth2Request.refresh
        in: query
        schema:
          type: boolean
      - name: OAuth2Request.refreshTokenRequest.grantType
        in: query
        schema:
          type: string
      - name: OAuth2Request.resourceIds
        in: query
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: OAuth2Request.responseTypes
        in: query
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: authenticated
        in: query
        schema:
          type: boolean
      - name: "authorities[0].authority"
        in: query
        schema:
          type: string
      - name: clientOnly
        in: query
        schema:
          type: boolean
      - name: credentials
        in: query
        schema:
          type: object
      - name: details
        in: query
        schema:
          type: object
      - name: name
        in: query
        schema:
          type: string
      - name: principal
        in: query
        schema:
          type: object
      - name: userAuthentication.authenticated
        in: query
        schema:
          type: boolean
      - name: "userAuthentication.authorities[0].authority"
        in: query
        schema:
          type: string
      - name: userAuthentication.credentials
        in: query
        schema:
          type: object
      - name: userAuthentication.details
        in: query
        schema:
          type: object
      - name: userAuthentication.principal
        in: query
        schema:
          type: object
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OperationCompletionRS'
      deprecated: false
  /sso/user:
    get:
      tags:
      - sso-endpoint
      summary: user
      operationId: userUsingGET_1
      parameters:
      - name: authenticated
        in: query
        schema:
          type: boolean
      - name: "authorities[0].authority"
        in: query
        schema:
          type: string
      - name: credentials
        in: query
        schema:
          type: object
      - name: details
        in: query
        schema:
          type: object
      - name: principal
        in: query
        schema:
          type: object
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
    post:
      tags:
      - sso-endpoint
      summary: user
      operationId: userUsingPOST_1
      parameters:
      - name: authenticated
        in: query
        schema:
          type: boolean
      - name: "authorities[0].authority"
        in: query
        schema:
          type: string
      - name: credentials
        in: query
        schema:
          type: object
      - name: details
        in: query
        schema:
          type: object
      - name: principal
        in: query
        schema:
          type: object
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
components:
  schemas:
    AbstractAuthResource:
      title: AbstractAuthResource
      type: object
      properties:
        type:
          type: string
    OAuthRegistrationResource:
      title: OAuthRegistrationResource
      type: object
      properties:
        authGrantType:
          type: string
        authorizationUri:
          type: string
        clientAuthMethod:
          type: string
        clientId:
          type: string
        clientName:
          type: string
        clientSecret:
          type: string
        id:
          type: string
        jwkSetUri:
          type: string
        redirectUrlTemplate:
          type: string
        restrictions:
          type: object
          additionalProperties:
            type: string
        scopes:
          type: array
          items:
            type: string
        tokenUri:
          type: string
        userInfoEndpointNameAttribute:
          type: string
        userInfoEndpointUri:
          type: string
    OperationCompletionRS:
      title: OperationCompletionRS
      type: object
      properties:
        message:
          type: string
    UpdateAuthRQ:
      title: UpdateAuthRQ
      type: object
      properties:
        enabled:
          type: boolean
        integrationParameters:
          type: object
          properties: {}
x-original-swagger-version: "2.0"
