/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const {
  versionSelector,
  versionCrumb,
} = require('docusaurus-plugin-openapi-docs/lib/sidebars/utils');

// const serviceApiVersions = require('./docs/api/service-api/versions.json');
const serviceUatVersions = require('./docs/api/service-uat/versions.json');

const apiSidebar = require('./docs/api/service-api/sidebar.ts');
const uatSidebar = require('./docs/api/service-uat/sidebar.ts');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  serviceApi: [
    // {
    //   type: 'html',
    //   defaultStyle: true,
    //   value: versionSelector(serviceApiVersions),
    //   className: 'version-button',
    // },
    // {
    //   type: 'html',
    //   defaultStyle: true,
    //   value: versionCrumb(`v5.10.1`),
    // },
    {
      type: 'category',
      label: 'Service API',
      link: {
        type: 'generated-index',
        title: 'ReportPortal Service API',
        description: 'This is a generated index of the ReportPortal Service API v5.10.1.',
        slug: '/category/api/service-api',
      },
      items: apiSidebar,
    },
  ],
  serviceUat: [
    {
      type: 'html',
      defaultStyle: true,
      value: versionSelector(serviceUatVersions),
      className: 'version-button',
    },
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v5.10.0`),
    },
    {
      type: 'category',
      label: 'Service UAT',
      link: {
        type: 'generated-index',
        title: 'ReportPortal Service UAT',
        description: 'This is a generated index of the ReportPortal Authtorization API.',
        slug: '/category/api/service-uat',
      },
      items: uatSidebar,
    },
  ],
};

module.exports = sidebars;
