/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const designSidebar = require('./docs/api/api-design/sidebar.ts');
const apiSidebars = require('./docs/api/sidebars/api-sidebars.ts');
const uatSidebars = require('./docs/api/sidebars/uat-sidebars.ts');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  apiDesign: [
    {
      type: 'category',
      label: 'API Documentation',
      link: {
        type: 'generated-index',
        title: 'ReportPortal API',
        description: 'This is a generated index of the ReportPortal API Documentation.',
        slug: '/category/api/api-design',
      },
      items: designSidebar,
    },
  ],
};

const joinedSidebars = {
  ...sidebars,
  ...apiSidebars,
  ...uatSidebars,
};

module.exports = joinedSidebars;
