openapi: 3.0.3
info:
  title: ReportPortal
  contact:
    email: support@reportportal.io
    name: Support
  description: Report Portal UAT documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 5.10.0
# Manual added section
servers:
  - url: '{protocol}://{authority}/uat'
    description: ReportPortal UAT server
    variables:
      protocol:
        default: https
        description: Protocol
        enum:
          - http
          - https
      authority:
        description: Host name and port (if needed) of Report Portal server
        default: demo.reportportal.io
# Manual added section
security:
  - bearerAuth: []
tags:
  - description: Auth Configuration Endpoint
    name: auth-configuration-endpoint
  - description: Github Endpoint
    name: github-endpoint
  - description: O Auth Configuration Endpoint
    name: o-auth-configuration-endpoint
  - description: Sso Endpoint
    name: sso-endpoint
paths:
  /settings/auth/{authType}:
    get:
      operationId: getSettings
      parameters:
        - in: path
          name: authType
          required: true
          schema:
            type: string
            enum:
              - ad
              - ldap
              - saml
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AbstractAuthResource'
          description: OK
      summary: Retrieves auth settings
      tags:
        - auth-configuration-endpoint
    post:
      operationId: createAuthIntegration
      parameters:
        - in: path
          name: authType
          required: true
          schema:
            type: string
            enum:
              - ad
              - ldap
              - saml
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthRQ'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AbstractAuthResource'
          description: OK
      summary: Create new auth integration
      tags:
        - auth-configuration-endpoint
  /settings/auth/{authType}/{integrationId}:
    put:
      operationId: updateAuthIntegration
      parameters:
        - in: path
          name: authType
          required: true
          schema:
            type: string
            enum:
              - ad
              - ldap
              - saml
        - in: path
          name: integrationId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthRQ'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AbstractAuthResource'
          description: OK
      summary: Update auth integration
      tags:
        - auth-configuration-endpoint
  /settings/auth/{integrationId}:
    delete:
      operationId: deleteSettings
      parameters:
        - in: path
          name: integrationId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OperationCompletionRS'
          description: OK
      summary: Retrieves auth settings
      tags:
        - auth-configuration-endpoint
  /settings/oauth:
    get:
      operationId: getOAuthSettings
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/OAuthRegistrationResource'
          description: OK
      summary: Returns OAuth Server Settings
      tags:
        - o-auth-configuration-endpoint
  /settings/oauth/{authId}:
    delete:
      operationId: deleteOAuthSetting
      parameters:
        - in: path
          name: authId
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OperationCompletionRS'
          description: OK
      summary: Deletes OAuth Integration Settings
      tags:
        - o-auth-configuration-endpoint
    get:
      operationId: getOAuthSettings_1
      parameters:
        - in: path
          name: authId
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OAuthRegistrationResource'
          description: OK
      summary: Returns OAuth Server Settings
      tags:
        - o-auth-configuration-endpoint
    post:
      operationId: updateOAuthSettings
      parameters:
        - in: path
          name: authId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthRegistrationResource'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OAuthRegistrationResource'
          description: OK
      summary: Creates/Updates OAuth Integration Settings
      tags:
        - o-auth-configuration-endpoint
    put:
      operationId: updateOAuthSettings_1
      parameters:
        - in: path
          name: authId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthRegistrationResource'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OAuthRegistrationResource'
          description: OK
      summary: Creates/Updates OAuth Integration Settings
      tags:
        - o-auth-configuration-endpoint
  /sso/me:
    get:
      operationId: user
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
          description: OK
      summary: Get user details
      tags:
        - sso-endpoint
    post:
      operationId: user_1
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
          description: OK
      summary: Get user details
      tags:
        - sso-endpoint
  /sso/me/github/synchronize:
    post:
      operationId: synchronize
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OperationCompletionRS'
          description: OK
      summary: Synchronizes logged-in GitHub user
      tags:
        - github-endpoint
  /sso/user:
    get:
      operationId: user_2
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
          description: OK
      summary: Get user details
      tags:
        - sso-endpoint
    post:
      operationId: user_3
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
          description: OK
      summary: Get user details
      tags:
        - sso-endpoint
components:
  schemas:
    AbstractAuthResource:
      type: object
      properties:
        type:
          type: string
    OAuthRegistrationResource:
      required:
        - clientId
        - clientSecret
      type: object
      properties:
        authGrantType:
          type: string
        authorizationUri:
          pattern: ^(http://|https://)?(www\.)?([a-zA-Z0-9-]+)(\.[a-zA-Z0-9-]+)*(:[0-9]+)?(/[a-z_-]+)*$
          type: string
          example: string
        clientAuthMethod:
          type: string
        clientId:
          type: string
        clientName:
          type: string
        clientSecret:
          type: string
        id:
          type: string
        jwkSetUri:
          type: string
        redirectUrlTemplate:
          type: string
        restrictions:
          type: object
          additionalProperties:
            type: string
        scopes:
          uniqueItems: true
          type: array
          items:
            type: string
        tokenUri:
          pattern: ^(http://|https://)?(www\.)?([a-zA-Z0-9-]+)(\.[a-zA-Z0-9-]+)*(:[0-9]+)?(/[a-z_-]+)*$
          type: string
          example: string
        userInfoEndpointNameAttribute:
          type: string
        userInfoEndpointUri:
          type: string
    OperationCompletionRS:
      type: object
      properties:
        message:
          type: string
    UpdateAuthRQ:
      required:
        - enabled
        - integrationParameters
      type: object
      properties:
        enabled:
          type: boolean
        integrationParameters:
          type: object
          additionalProperties:
            type: object
  # Manual added section
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
